name = "sharecraft"
main = "src/index.ts"
compatibility_date = "2024-03-20"

[build]
command = "bun run build"

[[d1_databases]]
binding = "DB"
database_name = "social_previews"
database_id = "your-database-id"

[[r2_buckets]]
binding = "PREVIEW_IMAGES"
bucket_name = "preview-images"

[[kv_namespaces]]
binding = "CONFIG"
id = "your-kv-namespace-id"
